version: '3.8'
services:
  web:
    build: ./web
    container_name: web
    volumes:
      - ./web/conf/:/etc/nginx/conf.d
      - ./web/uwsgi_params:/etc/nginx/uwsgi_params
      - ./web/static:/var/www/html/static
      #- ./web/ssl:/etc/ssl/app
    ports:
      - "8000:443"
      #- "443:443"
    depends_on:
      - back
    networks:
      - default

  db:
    build: ./db
    container_name: db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/mysql/:/var/lib/mysql/
      - ./db/.bashrc:/root/.bashrc
    networks:
      - default
  
  back:
    build: ./back
    container_name: back
    volumes: 
      - ./web/uwsgi.ini:/etc/uwsgi/uwsgi.ini
      - ./back:/opt/app
      - ./web/static:/opt/app/static
      - ./back/media/images:/opt/app/media/images
    expose:
      - "8001"
    depends_on:
      - db
    networks:
      - default

  # front:
  #   container_name: front
  #   build: ./front
  #   # command: 'sh /code/scripts/start.sh'
  #   volumes:
  #     - ./front:/code
  #     # - ./front/node_modules:/code/node_modules
  #   ports:
  #     - "8080:8080"
  #   expose:
  #     -  "3000"
  #   depends_on:
  #     -  back
  #   networks:
  #     - default

networks:
  default:
    driver: bridge

volumes:
  mysql: